name: smart_sheet
description: تطبيق لإدارة خطوط إنتاج مصانع الكرتون - Smart Sheet
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # تخزين محلي سريع (للـ cache، المقاسات، الإعدادات)
  hive: ^2.2.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # إدارة الحالة (State Management) - نستخدم Provider كأول خيار بسيط وقوي
  provider: ^6.1.2

  # اختيار الصور والتقاطها بالكاميرا
  image_picker: ^0.8.8+7

  # إنشاء ملفات PDF وتوليدها
  pdf: ^3.10.0
  printing: ^5.14.2 # تم التأكد من أحدث نسخة موجودة في lock file

  # رسوم متحركة (مثل Lottie في Splash أو Loading)
  lottie: ^2.7.0

  # تخزين الإعدادات (مثل الثيم، جودة الكاميرا)
  shared_preferences: ^2.2.2

  # للتعامل مع المسارات والملفات
  path: ^1.8.3

  # لو حابب تعمل ZIP للنسخة الاحتياطية
  archive: ^3.5.1

  # عمل deep link أو فتح سياسة الخصوصية في المتصفح
  url_launcher: ^6.3.2

  # لتحسين UI مع الحواف والزوايا (مفيد في الأزرار)
  flutter_screenutil: ^5.9.3

  # لتغيير اسم التطبيق (في وقت البناء)
  rename: ^3.1.0
  path_provider: ^2.1.5
  camera: ^0.11.2
  photo_view: ^0.15.0
  permission_handler: ^12.0.1
  math_expressions: ^3.0.0
  change_app_package_name: ^1.5.0
  device_info_plus: ^12.3.0
  open_file: ^3.5.10
  file_picker: ^10.3.7
  supabase_flutter: ^2.12.0
  flutter_image_compress: ^2.4.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # للتأكد من إغلاق boxes في Hive بعد الاختبارات
  mockito: ^5.4.4
  build_runner: 2.4.13


# إعدادات Flutter
flutter:
  # تفعيل توليد الأصول (مثل الصور والخطوط)
  generate: true

  # الأصول (Assets)
  # ممكن تفعيلها لاحقًا لما نضيف الصور أو الرموز
  assets:
    - assets/images/
  #   - assets/animations/
  #   - assets/icons/
  #   - assets/fonts/

  # الخطوط (مثال: Cairo للعربية)
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

  # دعم Material Design (يسمح باستخدام Material Icons)
  uses-material-design: true